export const PinataAPIKey = process.env.REACT_APP_PINATA_API_KEY;
export const PinataSecretKey = process.env.REACT_APP_PINATA_API_SECRET;

export const CONTRACT_ADDRESS_CAPX_ETHEREUM =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_ETHEREUM;
export const CONTRACT_ADDRESS_CAPX_CONTROLLER_ETHEREUM =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_CONTROLLER_ETHEREUM;

export const CONTRACT_ADDRESS_CAPX_MATIC =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_MATIC;
export const CONTRACT_ADDRESS_CAPX_CONTROLLER_MATIC =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_CONTROLLER_MATIC;

export const CONTRACT_ADDRESS_CAPX_BSC =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_BSC;
export const CONTRACT_ADDRESS_CAPX_CONTROLLER_BSC =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_CONTROLLER_BSC;

export const CONTRACT_ADDRESS_CAPX_AVALANCHE =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_AVALANCHE;
export const CONTRACT_ADDRESS_CAPX_CONTROLLER_AVALANCHE =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_CONTROLLER_AVALANCHE;

export const CONTRACT_ADDRESS_CAPX_FANTOM =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_FANTOM;
export const CONTRACT_ADDRESS_CAPX_CONTROLLER_FANTOM =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_CONTROLLER_FANTOM;

export const CONTRACT_ADDRESS_CAPX_MOONBEAM =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_MOONBEAM;
export const CONTRACT_ADDRESS_CAPX_CONTROLLER_MOONBEAM =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_CONTROLLER_MOONBEAM;

export const CONTRACT_ADDRESS_CAPX_ARBITRUM =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_ARBITRUM;
export const CONTRACT_ADDRESS_CAPX_CONTROLLER_ARBITRUM =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_CONTROLLER_ARBITRUM;

export const GRAPHAPIURL =
  process.env.REACT_APP_GRAPHAPIURL ||
  "https://api.thegraph.com/subgraphs/shreyas3336/vesting";
export const GRAPHAPIURL_WRAPPED_ETHEREUM =
  process.env.REACT_APP_GRAPHAPIURL_WRAPPED_ETHEREUM;
export const GRAPHAPIURL_VESTING_ETHEREUM =
  process.env.REACT_APP_GRAPHAPIURL_VESTING_ETHEREUM;
export const GRAPHAPIURL_MASTER_ETHEREUM =
  process.env.REACT_APP_GRAPHAPIURL_MASTER_ETHEREUM;

export const GRAPHAPIURL_WRAPPED_MATIC =
  process.env.REACT_APP_GRAPHAPIURL_WRAPPED_MATIC;
export const GRAPHAPIURL_VESTING_MATIC =
  process.env.REACT_APP_GRAPHAPIURL_VESTING_MATIC;
export const GRAPHAPIURL_MASTER_MATIC =
  process.env.REACT_APP_GRAPHAPIURL_MASTER_MATIC;

export const GRAPHAPIURL_WRAPPED_BSC =
  process.env.REACT_APP_GRAPHAPIURL_WRAPPED_BSC;
export const GRAPHAPIURL_VESTING_BSC =
  process.env.REACT_APP_GRAPHAPIURL_VESTING_BSC;
export const GRAPHAPIURL_MASTER_BSC =
  process.env.REACT_APP_GRAPHAPIURL_MASTER_BSC;

export const GRAPHAPIURL_WRAPPED_AVALANCHE =
  process.env.REACT_APP_GRAPHAPIURL_WRAPPED_AVALANCHE;
export const GRAPHAPIURL_VESTING_AVALANCHE =
  process.env.REACT_APP_GRAPHAPIURL_VESTING_AVALANCHE;
export const GRAPHAPIURL_MASTER_AVALANCHE =
  process.env.REACT_APP_GRAPHAPIURL_MASTER_AVALANCHE;

export const GRAPHAPIURL_WRAPPED_FANTOM =
  process.env.REACT_APP_GRAPHAPIURL_WRAPPED_FANTOM;
export const GRAPHAPIURL_VESTING_FANTOM =
  process.env.REACT_APP_GRAPHAPIURL_VESTING_FANTOM;
export const GRAPHAPIURL_MASTER_FANTOM =
  process.env.REACT_APP_GRAPHAPIURL_MASTER_FANTOM;

export const GRAPHAPIURL_WRAPPED_MOONBEAM =
  process.env.REACT_APP_GRAPHAPIURL_WRAPPED_MOONBEAM;
export const GRAPHAPIURL_VESTING_MOONBEAM =
  process.env.REACT_APP_GRAPHAPIURL_VESTING_MOONBEAM;
export const GRAPHAPIURL_MASTER_MOONBEAM =
  process.env.REACT_APP_GRAPHAPIURL_MASTER_MOONBEAM;

export const GRAPHAPIURL_WRAPPED_ARBITRUM =
  process.env.REACT_APP_GRAPHAPIURL_WRAPPED_ARBITRUM;
export const GRAPHAPIURL_VESTING_ARBITRUM =
  process.env.REACT_APP_GRAPHAPIURL_VESTING_ARBITRUM;
export const GRAPHAPIURL_MASTER_ARBITRUM =
  process.env.REACT_APP_GRAPHAPIURL_MASTER_ARBITRUM;

export const EXPLORER_ETHEREUM = process.env.REACT_APP_EXPLORER_ETHEREUM;
export const EXPLORER_BSC = process.env.REACT_APP_EXPLORER_BSC;
export const EXPLORER_MATIC = process.env.REACT_APP_EXPLORER_MATIC;
export const EXPLORER_AVALANCHE = process.env.REACT_APP_EXPLORER_AVALANCHE;
export const EXPLORER_FANTOM = process.env.REACT_APP_EXPLORER_FANTOM;
export const EXPLORER_MOONBEAM = process.env.REACT_APP_EXPLORER_MOONBEAM;
export const EXPLORER_ARBITRUM = process.env.REACT_APP_EXPLORER_ARBITRUM;

export const MATIC_CHAIN_ID = process.env.REACT_APP_MATIC_CHAIN_ID;
export const BSC_CHAIN_ID = process.env.REACT_APP_BSC_CHAIN_ID;
export const ETHEREUM_CHAIN_ID = process.env.REACT_APP_ETHEREUM_CHAIN_ID;
export const AVALANCHE_CHAIN_ID = process.env.REACT_APP_AVALANCHE_CHAIN_ID;
export const FANTOM_CHAIN_ID = process.env.REACT_APP_FANTOM_CHAIN_ID;
export const MOONBEAM_CHAIN_ID = process.env.REACT_APP_MOONBEAM_CHAIN_ID;
export const ARBITRUM_CHAIN_ID = process.env.REACT_APP_ARBITRUM_CHAIN_ID;

export const CHAIN_NAMES = process.env.REACT_APP_CHAIN_NAMES;
