const tokenTypeData = [
  {
    id: "f01",
    name: "Standard Token",
    description: "Token Description",
    features: {
      "ERC 20 Compliant": true,
      Mintable: false,
      "Liquidity Generator": false,
      "Verified Source Code": true,
      Burnable: false,
      "Donation (Charity)": true,
      Ownable: false,
      Pausable: false,
      "Yield Generator": false,
      "Capped Total Supply": false,
      "Taxable (Burn Tax)": false,
    },
    advancedFeatures: "00000000",
  },
  {
    id: "f02",
    name: "Mintable Token",
    description: "Token Description",
    features: {
      "ERC 20 Compliant": true,
      Mintable: true,
      "Liquidity Generator": true,
      "Verified Source Code": true,
      Burnable: false,
      "Donation (Charity)": true,
      Ownable: false,
      Pausable: false,
      "Yield Generator": false,
      "Capped Total Supply": false,
      "Taxable (Burn Tax)": false,
    },
    advancedFeatures: "00000000",
  },
  {
    id: "f03",
    name: "Burnable Token",
    description: "Token Description",
    features: {
      "ERC 20 Compliant": true,
      Mintable: false,
      "Liquidity Generator": true,
      "Verified Source Code": true,
      Burnable: true,
      "Donation (Charity)": true,
      Ownable: false,
      Pausable: false,
      "Yield Generator": false,
      "Capped Total Supply": false,
      "Taxable (Burn Tax)": false,
    },
    advancedFeatures: "00000000",
  },
  {
    id: "f04",
    name: "Mintable & Burnable Token",
    description: "Token Description",
    features: {
      "ERC 20 Compliant": true,
      Mintable: true,
      "Liquidity Generator": true,
      "Verified Source Code": true,
      Burnable: true,
      "Donation (Charity)": true,
      Ownable: false,
      Pausable: false,
      "Yield Generator": false,
      "Capped Total Supply": false,
      "Taxable (Burn Tax)": false,
    },
    advancedFeatures: "00000000",
  },
  {
    id: "f05",
    name: "Pausable Standard Token",
    description: "Token Description",
    features: {
      "ERC 20 Compliant": true,
      Mintable: false,
      "Liquidity Generator": true,
      "Verified Source Code": true,
      Burnable: false,
      "Donation (Charity)": true,
      Ownable: false,
      Pausable: true,
      "Yield Generator": false,
      "Capped Total Supply": false,
      "Taxable (Burn Tax)": false,
    },
    advancedFeatures: "00000000",
  },
  {
    id: "f06",
    name: "Pausable Mintable Token",
    description: "Token Description",
    features: {
      "ERC 20 Compliant": true,
      Mintable: true,
      "Liquidity Generator": true,
      "Verified Source Code": true,
      Burnable: false,
      "Donation (Charity)": true,
      Ownable: false,
      Pausable: true,
      "Yield Generator": false,
      "Capped Total Supply": false,
      "Taxable (Burn Tax)": false,
    },
    advancedFeatures: "00000000",
  },
  {
    id: "f07",
    name: "Pausable Burnable Token",
    description: "Token Description",
    features: {
      "ERC 20 Compliant": true,
      Mintable: false,
      "Liquidity Generator": true,
      "Verified Source Code": true,
      Burnable: true,
      "Donation (Charity)": true,
      Ownable: false,
      Pausable: false,
      "Yield Generator": false,
      "Capped Total Supply": false,
      "Taxable (Burn Tax)": false,
    },
    advancedFeatures: "00000000",
  },
  {
    id: "f08",
    name: "Pausable Mint&Burnable Token",
    description: "Token Description",
    features: {
      "ERC 20 Compliant": true,
      Mintable: true,
      "Liquidity Generator": true,
      "Verified Source Code": true,
      Burnable: true,
      "Donation (Charity)": true,
      Ownable: false,
      Pausable: true,
      "Yield Generator": false,
      "Capped Total Supply": false,
      "Taxable (Burn Tax)": false,
    },
    advancedFeatures: "00000000",
  },
  
];

export default tokenTypeData;
